### ISSUE TITLE
Keep emphasis or remove redundancy in CoC harassment section

### ISSUE THREAD

**Issue by alesandroortiz** [lgbtq-technology/lgbtq-technology.github.io#15]
With PR https://github.com/lgbtq-technology/lgbtq-technology.github.io/pull/14, `national origin`, `ethnic origin` and `nationality` have been added to the CoC's harrassment section.

Should we remove the now somewhat redundant `anti-Indigenous/Nativeness and anti-Blackness`? If it's for emphasis, and we're okay emphasizing forms of harrassment which are more relevant to the tech community, I'm okay with keeping. However, we should be careful to not start a "which form of harrassment is more important/relevant" competition, especially outside of the context of the tech community.

**Comment by yardenac** [comment]
I'm not sure what happened over the past 5.5 years, but the language mentioned appears to no longer be in the CoC, so I'm closing this. Thanks.
